config/routes.rb
Rails.application.routes.draw do
  get 'artciles/index'

  resources :articles

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
                      length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
	  @articles = Article.all
	end

	def show
	  @article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
      @article = Article.find(params[:id])
    end

	def create
	  @article = Article.new(article_params)

	  if @article.save
	    redirect_to @article
	  else
	  	render 'new'
	  end
    end

    def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
      	redirect_to @article
      else
      	render 'edit'
      end
    end

    private
      def article_params
      	params.require(:article).permit(:title, :text)
      end
end

app/controllers/welome_controller.rb
class WelomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welome_helper.rb
module WelomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_with(model: @article, local: true) do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<table class="table  " style ="border-style: solid;
    border-color: #20B2AA; border-width: 5px; width: 92%">
  <tr>
    <th class="text-center">offer</th>
    <th class="text-center">description</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article), class: 'btn btn-primary'  %></td>
    </tr>
  <% end %>
</table>

<div class="card">
  <% @articles.each do |article| %>
  <div class="card-block" style ="border-style: solid; border-color: #20B2AA;
 padding: 9px; border-width: 5px; background-color: #ADD8E6;
 width: 92%; margin: 0px auto; margin-bottom: 10px; border-radius: 8px">
    <h3 class="card-title"><%= article.title %></h3>
    <h6 class="card-subtitle mb-2 text-muted"><%= article.title %></h6>
    <p class="card-text"><%= article.text %></p>
    <a><%= link_to 'Show', article_path(article), class: 'btn btn-primary' %> </a>
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BBStock</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd; border-bottom: 5px solid; border-color: #20B2AA;" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="https://bitinfocharts.com/img/bitcoin%20gold.png">
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Create new lot!', new_article_path, class: 'btn btn-success' %>
</li>
    </ul>
  </div>
</nav>

app/views/welome/index.html.erb
    <h1>Hello, Rails!</h1>
    <%= link_to 'My Blog', controller: 'articles' %>
    